version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Bind mount source code for hot reload
      - ./backend:/app
      # Use named volume for venv to avoid permission issues
      - backend-venv:/app/.venv
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # GitHub API configuration
      - GH_TOKEN=${GH_TOKEN}
      - GH_REPO=${GH_REPO:-trakrf/action-spec}
      - SPECS_PATH=${SPECS_PATH:-infra}
      - WORKFLOW_BRANCH=${WORKFLOW_BRANCH:-main}
    env_file:
      - .env.local
    command: uv run flask --app app run --debug --host 0.0.0.0
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      # Bind mount source code for HMR
      - ./frontend:/app
      # Use named volume for node_modules to avoid platform issues
      - frontend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  backend-venv:
  frontend-node-modules:
