version = 0.1

[default]
[default.global.parameters]
stack_name = "actionspec-backend"
resolve_s3 = true

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "${AWS_REGION}"  # Read from environment
parameter_overrides = [
    "Environment=${ENVIRONMENT}",
    "GithubTokenParamName=${GITHUB_TOKEN_SSM_PARAM}"
]

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_invoke.parameters]
env_vars = "env.json"

[demo]
[demo.deploy.parameters]
stack_name = "actionspec-backend-demo"
region = "us-west-2"
parameter_overrides = [
    "Environment=demo"
]

[local]
[local.deploy.parameters]
stack_name = "actionspec-backend-local"
parameter_overrides = [
    "Environment=local"
]
