name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secret-scanning:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for TruffleHog

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  pattern-check:
    name: Check Infrastructure Patterns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for AWS Account IDs
        run: |
          # Exclude standard directories, ignore comments, and skip common test IDs + official AWS AMI publishers
          # Test/Example IDs: 000000000000, 111111111111, 999999999999, 123456789012
          # Official AMI Publishers:
          #   099720109477 = Canonical (Ubuntu AMIs)
          #   801119661308 = Microsoft (Windows Server AMIs)
          #   137112412989 = Amazon Linux AMIs
          #   591542846629 = AWS Marketplace
          #   679593333241 = AWS Deep Learning AMIs
          #   898082745236 = AWS ECS-Optimized AMIs
          if grep -r --exclude-dir={node_modules,.git,dist,build} \
             -E "[0-9]{12}" \
             --include="*.tf" --include="*.py" --include="*.js" \
             --include="*.yml" --include="*.yaml" . | \
             grep -vE "(nosec|security:ignore)" | \
             grep -vE "(000000000000|111111111111|999999999999|123456789012|099720109477|801119661308|137112412989|591542846629|679593333241|898082745236)"; then
            echo "❌ Found AWS account ID patterns"
            echo "Review and use variables instead of hardcoded IDs"
            echo "Or add # nosec comment to acknowledge intentional use"
            exit 1
          fi
          echo "✅ No AWS account IDs found (test IDs and official AMI publishers allowed)"

      - name: Check for Private IP Addresses
        run: |
          # Exclude standard directories, lock files, and lines with ignore comments
          if grep -r --exclude-dir={node_modules,.git,dist,build} \
             --exclude="*-lock.yaml" --exclude="*-lock.json" --exclude="package-lock.json" \
             -E "10\.|172\.(1[6-9]|2[0-9]|3[01])\.|192\.168\." \
             --include="*.tf" --include="*.yml" --include="*.yaml" . | \
             grep -vE "(nosec|security:ignore)"; then
            echo "❌ Found private IP address patterns"
            echo "Review and use variables instead of hardcoded IPs"
            echo "Or add # nosec comment to acknowledge intentional use"
            exit 1
          fi
          echo "✅ No private IP addresses found"

  pre-commit-validation:
    name: Pre-commit Hook Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run pre-commit checks
        run: ./scripts/pre-commit-checks.sh
